image:https://img.shields.io/github/v/release/jlanzarotta/timetracker[GitHub Release]

= Time Tracker
:toc: left
:toclevels: 6
:icons: font
:sectnums:
:numbered:
:table-stripes: even

== Overview

Time Tracker is a simple command line tool use to track the time you spend on a
specific project and the one or more tasks associated with that project.  It was
inspired by the concepts of utt (Ultimate Time Tracker) and timetrap.

== Installation

To install Time Tracker, simply unzip the archive for your specific operating system into the directory of your choice.

== Natural Language Time

Time Tracker supports natural language time constructs for a subset of
commands.  Commands such as hello, add, break, and stretch have additional parameters
that accept time an argument.  Any time you pass a time, Time Tracker will try
to parse it as a natural language time.

This feature can be very handy if you start a project/task and forget to add it simply by specifying the `--at` subcommand.

[source, shell]
----
$ tt hello --at "18 minutes ago"
----

The previous example tells Time Tracker that you want it to add a <<hello>> entry
with the time that was 18 minutes ago.

[source, shell]
----
$ tt break lunch --at "12:30"
----

The previous example tells Time Tracker that you want it to add a <<break>> entry
with the time that was at specifically "12:30PM".

[source, shell]
----
$ tt add project+task -- at "13:45"
----

The previous example tells Time Tracker that you want it to add an entry
with the time that was at specifically "13:45".

For more information about Natural Language Time as well as samples, head over
to [https://pkg.go.dev/github.com/ijt/go-anytime]

== Positional Commands

Time Tracker has many commands for the user to use:

=== hello

The `hello` command tells Time Tracker you have arrived and to start tracking
time.  This should be the first command you execute at the start of your day.

[source, shell]
----
$ tt hello
----

WARNING: Keep in mind that if you forget to execute the `hello` command at the start of the day, Time Tracker will think you worked throughout the night and calculate your time spent on your task accordingly when you run a `report`.  This may or may not be correct outcome.

=== add

The `add` command tells Time Tracker that you would like to record a project with optional one or more tasks you have just finished working on.

[source, shell]
----
$ tt add timetracker+programming
----

The previous command tells Time Tracker that you just finished working on the project(timetracker) and the task(programming).

[source, shell]
----
$ tt add timetracker+programming+documentation
----

The previous command tells Time Tracker that you just finished working on the project(timetracker) and the task(programming and documentation).

==== comment

The `comment` command tells Time Tracker that you would like to add a comment associated with your new entry.

[source, shell]
----
$ tt add timetracker+programming --comment "I love programming."
----

==== favorite

The `favorite` command tells Time Tracker that you would like to use one of your preconfigured favorite project/task combinations.  These favorites are stored in the _timetracker.yaml_ file which is located in the installation directory.  By default, there are 5 preconfigured favorites; however, you can add as many as you would like.

NOTE: Favorites are zero (0) based.

Favorites are in the following format:

[source,properties]
----
favorites:
  - favorite: general+training
  - favorite: general+product development
  - favorite: general+personal time
  - favorite: general+holiday
  - favorite: general+vacation/PTO/Comp
.
.
.
----

[source, shell]
----
$ tt add --favorite 0
Adding Project[general] Task[training] Date[2023-12-07T14:10:02-05:00]
----

The previous command tells Time Tracker that you just finished working on the favorite referenced by the number '0'.  If we look in our _timetracker.yaml_ file for the '0' favorite, we find that it references the 'project1+task1' combination.  With that, 'project1+task1' would be automatically logged as being completed.

TIP: Configuring and using favorites, help improve consistency as well as improves speed of entering frequently used project/task combinations.

=== break

The `break` command tells Time Tracker that you are going went on a break.  The time associated with breaks are not added to your daily work time.  They are consider under the break classification when doing a `report'.

[source, shell]
----
$ tt break lunch
----

The previous command tells Time Tracker that you just finished your lunch break.

=== edit

The `edit` command tells Time Tracker you would like to edit the data file with the default system editor.

=== show

The `show` command tells Time Tracker you would like to show various information.

==== favorites

The `favorites` command tells Time Tracker that you would like to show all your currently configured favorites that are stored in the _timetracker.yaml_ file which is located in the installation directory.

[source, shell]
----
$ tt show --favorites
Favorite 0: [general+training]
Favorite 1: [general+product development]
Favorite 2: [general+personal time]
Favorite 3: [general+holiday]
Favorite 4: [general+vacation/PTO/Comp]
----

=== report

The `report` command tells Time Tracker you would like to run a report on your activities.  By default, you get the current days activities.

==== Options

The `report` command had several handy options what allow you to customize what needs to be reported.

===== date

By specifying a date, this tells Time Tracker you would like to have a report for that specific date only.  The date MUST be in the following format `YYYY-mm-dd`.

[source, shell]
----
$ tt report 2019-04-05
----

===== --current-week

By specifying the option `--current-week`, this tells Time Tracker you would like a report for the current week's activities.

[source, shell]
----
$ tt report --current-week
----

===== --previous-week

By specifying the option `--previous-week`, this tells Time Tracker you would like a report for the previous week's activities.

[source, shell]
----
$ tt report --previous-week
----

===== --last-entry

By specifying the option `--last-entry`, this tells Time Tracker you would like a report for just the last entry's activity.

[source, shell]
----
$ tt report --last-entry
----

===== --from

By specifying the option `--from` _date_, this tells Time Tracker you would the report to start from this specific date.

[source, shell]
----
$ tt report --from 2019-03-02
----

===== --to

By specifying the option `--to` _date_, this tells Time Tracker you would the report to end at this specific date.

[source, shell]
----
$ tt report --to 2019-03-02
----

===== --no-rounding

By specifying the option `--no-rounding`, this tells Time Tracker you would
the all the duration to be their original, unrounded values.  This option is good it you have durations that are
less than the value you have configured for rounding.

[source, shell]
----
$ tt report --from 2019-04-01 --to 2019-04-13 --no-rounding
$ tt report --previous-week --no-rounding
----

=== stretch

Stretches the last entry to the current or specified date/time.

In the below example, the latest entry to 05-Dec-2023...  Time Tracker will as you if you want to perform the stretch or not.  If you enter (y or Yes), the latest entry is stretched.  If you enter (n/No), the latest entry is not stretched.

[source, shell]
----
$ tt stretch 
Would you like to stretch Project[***hello] to Tuesday, 05-Dec-2023 13:48:32 EST? (Y/N (yes/no)) yes
Last entry was stretched.                                                                           
----

== Copyright and License

BSD 3-Clause License

Copyright (c) 2018-{localyear}, Jeff Lanzarotta
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,this list of conditions, and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
